const DB_NAME='xian-library';const DB_VERSION=1;const MAX_FILE=15*1024*1024;
const TYPES=['弹唱','指弹','Solo','练习曲'];const MASTERY=['拿手歌','基本会','需要复习','正在学'];
const DEMOS=[
 {id:'demo-qingtian',title:'晴天',artist:'周杰伦',genres:['流行'],type:'弹唱',mastery:'需要复习',favorite:true,tags:['校园','治愈'],notes:'示例歌曲。换成你自己的谱图后，就可以开始记录练习。',demo:true},
 {id:'demo-chengdu',title:'成都',artist:'赵雷',genres:['民谣'],type:'弹唱',mastery:'基本会',favorite:false,tags:['治愈','城市'],notes:'慢一点，给每个和弦留足呼吸。',demo:true},
 {id:'demo-suddenly',title:'突然好想你',artist:'五月天',genres:['流行','摇滚'],type:'弹唱',mastery:'正在学',favorite:true,tags:['乐队','抒情'],notes:'副歌控制动态，不要一开始就太满。',demo:true},
 {id:'demo-sea',title:'海阔天空',artist:'Beyond',genres:['摇滚'],type:'Solo',mastery:'拿手歌',favorite:true,tags:['经典','粤语'],notes:'间奏是这首歌最有力量的部分。',demo:true},
 {id:'demo-road',title:'平凡之路',artist:'朴树',genres:['民谣','流行'],type:'弹唱',mastery:'基本会',favorite:false,tags:['公路','经典'],notes:'保持稳定的八分音符律动。',demo:true},
 {id:'demo-star',title:'七里香',artist:'周杰伦',genres:['流行'],type:'指弹',mastery:'需要复习',favorite:false,tags:['夏天','校园'],notes:'先慢速把旋律声部弹清楚。',demo:true}
];
const now=Date.now();DEMOS.forEach((s,i)=>{s.createdAt=now-i*86400000;s.updatedAt=now-i*86400000});
let db;let songs=[];let logs=[];let draftPages=[];let mobilePage=0;let practiceZoom=100;let reviewSelection=[];let filters={search:'',groups:{artist:new Set(),genre:new Set(),type:new Set(),mastery:new Set(),tag:new Set()},favorite:false};
const scorePageCache=new Map();const scoreObjectUrls=new Map();const previewWarmers=new Map();
const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
function uid(p='id'){return `${p}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
const ICONS={
 guitar:'<path d="M20.7 4.3 18 7l-1.3-1.3-2.1 2.1 1.3 1.3-4.1 4.1a4.5 4.5 0 1 0 2.9 2.9l4.1-4.1 1.3 1.3 2.1-2.1-1.3-1.3L23.6 7z"/><circle cx="9.5" cy="17.5" r="1.6"/>',
 home:'<path d="m3 11 9-8 9 8"/><path d="M5 10v10h14V10M9 20v-6h6v6"/>',
 grid:'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',
 book:'<path d="M4 5.5A2.5 2.5 0 0 1 6.5 3H20v16H6.5A2.5 2.5 0 0 0 4 21.5z"/><path d="M4 5.5v16M8 7h8M8 11h8"/>',
 heart:'<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8z"/>',
 clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3.5 2"/>',
 tag:'<path d="M20 13 13 20l-9-9V4h7z"/><circle cx="8.5" cy="8.5" r="1"/>',
 settings:'<circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .3 1.9l.1.1-2.8 2.8-.1-.1a1.7 1.7 0 0 0-1.9-.3 1.7 1.7 0 0 0-1 1.6v.2h-4V21a1.7 1.7 0 0 0-1-1.6 1.7 1.7 0 0 0-1.9.3l-.1.1L4.2 17l.1-.1a1.7 1.7 0 0 0 .3-1.9A1.7 1.7 0 0 0 3 14H2.8v-4H3a1.7 1.7 0 0 0 1.6-1 1.7 1.7 0 0 0-.3-1.9L4.2 7 7 4.2l.1.1A1.7 1.7 0 0 0 9 4.6 1.7 1.7 0 0 0 10 3v-.2h4V3a1.7 1.7 0 0 0 1 1.6 1.7 1.7 0 0 0 1.9-.3l.1-.1L19.8 7l-.1.1a1.7 1.7 0 0 0-.3 1.9 1.7 1.7 0 0 0 1.6 1h.2v4H21a1.7 1.7 0 0 0-1.6 1z"/>',
 shuffle:'<path d="M16 3h5v5M4 20 21 3M21 16v5h-5M15 15l6 6M4 4l5 5"/>',
 star:'<path d="m12 2.7 2.9 5.9 6.5.9-4.7 4.6 1.1 6.5-5.8-3-5.8 3 1.1-6.5-4.7-4.6 6.5-.9z"/>',
 learn:'<path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20V4H6.5A2.5 2.5 0 0 0 4 6.5z"/><path d="M8 8h8M8 12h6"/>',
 user:'<circle cx="12" cy="7" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/>',
 music:'<path d="M9 18V5l11-2v13"/><circle cx="6" cy="18" r="3"/><circle cx="17" cy="16" r="3"/>',
 bars:'<path d="M5 20V10M12 20V4M19 20v-7"/>',
 sync:'<path d="M20 7h-5V2M4 17h5v5"/><path d="M5.7 9A7 7 0 0 1 17.8 5L20 7M4 17l2.2 2A7 7 0 0 0 18.3 15"/>',
 monitor:'<rect x="3" y="4" width="18" height="13" rx="2"/><path d="M8 21h8M12 17v4"/>'
};
function icon(name,label=''){return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" aria-hidden="${label?'false':'true'}"${label?` aria-label="${esc(label)}"`:''}>${ICONS[name]||ICONS.music}</svg>`}
const QUICK_ICONS={
 random:'<path d="M6.5 7.5h2.1c3.8 0 4.9 9 8.8 9h1.1"/><path d="M6.5 16.5h2.1c1.8 0 3-2 4.2-4.2 1.2-2.3 2.3-4.8 4.6-4.8h1.1"/><path d="m16.5 5.5 2 2-2 2M16.5 14.5l2 2-2 2"/><circle cx="5" cy="7.5" r="1"/><circle cx="5" cy="16.5" r="1"/>',
 old:'<circle cx="12" cy="12" r="6.8"/><path d="M12 8.2v4.2l2.8 1.7"/><path d="M5.2 5.2 3.7 3.7M18.8 5.2l1.5-1.5"/>',
 master:'<path d="m12 4.2 2.1 4.3 4.8.7-3.5 3.4.8 4.8-4.2-2.2-4.2 2.2.8-4.8-3.5-3.4 4.8-.7z"/><circle cx="12" cy="12" r="9" stroke-dasharray="1 3"/>',
 learning:'<path d="M4.5 6.3c2.7-.9 5-.4 7.5 1.4v10.1c-2.5-1.8-4.8-2.3-7.5-1.4zM19.5 6.3c-2.7-.9-5-.4-7.5 1.4v10.1c2.5-1.8 4.8-2.3 7.5-1.4z"/><path d="M12 7.7v10.1M16.5 9.2l-2.2.4"/>'
};
function quickIcon(name){return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${QUICK_ICONS[name]}</svg>`}
function coverClass(s){return s.id==='demo-qingtian'?'cover-qingtian':s.id==='demo-chengdu'?'cover-chengdu':s.id==='demo-suddenly'?'cover-suddenly':'cover-default'}
function compactMediaUrl(url='',kind='cover'){const size=kind==='artist'?'150':kind==='wide'?'300':'180';return String(url).replace(/R(?:500|300|180|150)x(?:500|300|180|150)/i,`R${size}x${size}`)}
function songCover(s,className='library-cover'){const wide=className==='cover',priority=wide||className==='review-thumb',kind=wide?'wide':'cover';return `<span class="${className} ${coverClass(s)}" aria-hidden="true">${s.coverUrl?`<img src="${esc(compactMediaUrl(s.coverUrl,kind))}" alt="" loading="${priority?'eager':'lazy'}" decoding="async">`:''}</span>`}
function artistAvatar(artist,className='artist-avatar'){const image=songs.find(song=>song.artist===artist&&song.artistImageUrl)?.artistImageUrl;return `<span class="${className}">${image?`<img src="${esc(compactMediaUrl(image,'artist'))}" alt="" loading="lazy" decoding="async">`:esc(artist.slice(0,1))}</span>`}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2200)}
function openDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,DB_VERSION);req.onupgradeneeded=()=>{const d=req.result;if(!d.objectStoreNames.contains('songs'))d.createObjectStore('songs',{keyPath:'id'});if(!d.objectStoreNames.contains('pages')){const s=d.createObjectStore('pages',{keyPath:'id'});s.createIndex('songId','songId')}if(!d.objectStoreNames.contains('logs')){const s=d.createObjectStore('logs',{keyPath:'id'});s.createIndex('songId','songId')}};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
function store(name,mode='readonly'){return db.transaction(name,mode).objectStore(name)}
function reqP(req){return new Promise((res,rej)=>{req.onsuccess=()=>res(req.result);req.onerror=()=>rej(req.error)})}
const repo={
 listSongs:()=>reqP(store('songs').getAll()),getSong:id=>reqP(store('songs').get(id)),
 saveSong:s=>reqP(store('songs','readwrite').put(s)),deleteSong:async id=>{await reqP(store('songs','readwrite').delete(id));const pages=await repo.getPages(id);const tx=db.transaction(['pages','logs'],'readwrite');pages.forEach(p=>tx.objectStore('pages').delete(p.id));const allLogs=await reqP(tx.objectStore('logs').index('songId').getAll(id));allLogs.forEach(l=>tx.objectStore('logs').delete(l.id));return new Promise((r,j)=>{tx.oncomplete=r;tx.onerror=()=>j(tx.error)})},
 getPages:id=>reqP(store('pages').index('songId').getAll(id)).then(a=>a.sort((a,b)=>a.order-b.order)),
 savePages:async(songId,pages)=>{const old=await repo.getPages(songId);const tx=db.transaction('pages','readwrite');old.forEach(p=>tx.objectStore('pages').delete(p.id));pages.forEach((p,i)=>tx.objectStore('pages').put({...p,songId,order:i}));return new Promise((r,j)=>{tx.oncomplete=r;tx.onerror=()=>j(tx.error)})},
 listLogs:()=>reqP(store('logs').getAll()),recordPractice:async(songId,rating)=>{const song=await repo.getSong(songId);if(!song)throw Error('歌曲不存在');const mastery=rating==='熟练'?'拿手歌':rating==='遗忘'?'需要复习':'正在学';const log={id:uid('log'),songId,rating,completedAt:Date.now()};const tx=db.transaction(['songs','logs'],'readwrite');tx.objectStore('logs').put(log);tx.objectStore('songs').put({...song,mastery,updatedAt:Date.now()});return new Promise((r,j)=>{tx.oncomplete=()=>r(log);tx.onerror=()=>j(tx.error)})}
};
async function seed(){if(localStorage.getItem('xian-seeded'))return;for(const s of DEMOS)await repo.saveSong(s);await repo.recordPractice('demo-sea','熟练');await repo.recordPractice('demo-star','遗忘');localStorage.setItem('xian-seeded','1')}
async function refresh(){songs=await repo.listSongs();if(songs.some(song=>!song.demo)&&songs.some(song=>song.demo)){for(const demo of songs.filter(song=>song.demo))await repo.deleteSong(demo.id);songs=await repo.listSongs()}logs=await repo.listLogs();songs.sort((a,b)=>b.updatedAt-a.updatedAt)}
let installPrompt=null;
let catalogStatus=navigator.onLine?'正在检查曲库更新…':'离线使用中';
function setSyncStatus(text,state='online'){catalogStatus=text;const el=$('#sync-status');if(!el)return;el.className=`sync-row ${state}`;const label=$('span',el);if(label)label.textContent=text}
const hiddenCatalogIds=()=>new Set(JSON.parse(localStorage.getItem('xian-hidden-catalog-ids')||'[]'));
async function pullCatalog(){
  if(!navigator.onLine){setSyncStatus('离线使用中','offline');return}
  const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),12000);
  try{
    setSyncStatus('正在检查曲库更新…','syncing');
    const response=await fetch('./catalog/scores.json',{cache:'no-cache',signal:controller.signal});
    if(!response.ok||!response.headers.get('content-type')?.includes('json'))throw Error('曲库清单暂不可用');
    const data=await response.json(),hidden=hiddenCatalogIds();
    for(const id of data.deletedIds||[]){const local=await repo.getSong(id);if(local?.catalogManaged)await deleteSongLocal(id)}
    for(const remote of data.songs||[]){
      if(hidden.has(remote.id))continue;
      const local=await repo.getSong(remote.id),version=Number(remote.updatedAt)||0;
      if(local?.localOverride||local?.remoteUpdatedAt>=version)continue;
      const {pages:remotePages,...metadata}=remote;
      await repo.saveSong({...metadata,mastery:local?.mastery||remote.initialMastery||'正在学',favorite:local?.favorite??remote.favorite,catalogManaged:true,remoteUpdatedAt:version,updatedAt:Math.max(version,Number(local?.updatedAt)||0)});
      await savePagesLocal(remote.id,remotePages.map(page=>({id:page.id,fileName:page.fileName,mimeType:page.mimeType,size:page.size,remoteUrl:page.url,createdAt:page.createdAt,order:page.order})));
      scorePageCache.delete(remote.id);
    }
    await refresh();setSyncStatus('曲库已更新');render();
  }catch(error){console.info('Catalog update deferred:',error.message);setSyncStatus('本机可用 · 更新待重试','offline')}
  finally{clearTimeout(timer)}
}
async function installApp(){if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;render();return}toast('请在浏览器菜单中选择“安装弦库”或“安装此站点作为应用”')}
const savePagesLocal=repo.savePages.bind(repo);repo.savePages=async(songId,pages)=>{await savePagesLocal(songId,pages);scorePageCache.delete(songId)};
const deleteSongLocal=repo.deleteSong.bind(repo);repo.deleteSong=async id=>{const song=await repo.getSong(id);await deleteSongLocal(id);scorePageCache.delete(id);if(song?.catalogManaged){const hidden=hiddenCatalogIds();hidden.add(id);localStorage.setItem('xian-hidden-catalog-ids',JSON.stringify([...hidden]))}};
const shellBase=shell;shell=content=>{const installMarkup=window.matchMedia?.('(display-mode: standalone)').matches?'':`<button class="secondary install-button" type="button" data-install>${icon('monitor')} 安装到电脑</button>`;return shellBase(content.replace('谱图与练习记录只保存在当前浏览器。清除网站数据会删除曲库。','公开曲库会随网站更新；自己添加的谱图、练习记录和熟练度只保存在当前设备。')).replace('<a class="settings-link"',`${installMarkup}<a class="settings-link"`)};
const nav=[['/','home','首页'],['/features','grid','功能'],['/library','book','我的曲谱'],['/favorites','heart','收藏'],['/history','clock','练习记录'],['/tags','tag','我的标签']];
function route(){return (location.hash.slice(1)||'/').split('?')[0]}
function isActive(path){const r=route();return path==='/'?r==='/':r.startsWith(path)}
function shell(content){const online=navigator.onLine;return `<div class="app-shell"><aside class="sidebar"><div class="brand"><span class="brand-mark">${icon('guitar')}</span><span>弦库</span></div><div class="sync-row ${online?'':'offline'}" id="sync-status">${icon('sync')}<span>${catalogStatus}</span><i class="sync-dot"></i></div><nav class="nav-list">${nav.map(n=>`<a class="nav-item ${isActive(n[0])?'active':''}" href="#${n[0]}"><span class="nav-icon">${icon(n[1])}</span>${n[2]}</a>`).join('')}</nav><a class="settings-link" href="#/settings"><span class="nav-icon">${icon('settings')}</span>设置</a></aside><main class="main">${content}</main><nav class="mobile-nav">${nav.slice(0,3).concat([['/favorites','heart','收藏']]).map(n=>`<a class="${isActive(n[0])?'active':''}" href="#${n[0]}"><span class="nav-icon">${icon(n[1])}</span>${n[2]}</a>`).join('')}</nav></div>`}
function lastLog(id){return logs.filter(l=>l.songId===id).sort((a,b)=>b.completedAt-a.completedAt)[0]}
const LONG_UNPLAYED_DAYS=30;
function longUnplayedSongs(){const cutoff=Date.now()-LONG_UNPLAYED_DAYS*86400000;return songs.filter(s=>!lastLog(s.id)||lastLog(s.id).completedAt<cutoff).sort((a,b)=>(lastLog(a.id)?.completedAt||0)-(lastLog(b.id)?.completedAt||0))}
function shuffled(values){const copy=[...values];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]]}return copy}
function suggestedReviewSongs(reset=false){const pool=longUnplayedSongs(),byId=new Map(pool.map(song=>[song.id,song]));if(!reset&&reviewSelection.length){const kept=reviewSelection.map(id=>byId.get(id)).filter(Boolean);if(kept.length===Math.min(3,pool.length))return kept}if(reset){const current=new Set(reviewSelection),fresh=shuffled(pool.filter(song=>!current.has(song.id))),previous=shuffled(pool.filter(song=>current.has(song.id)));reviewSelection=[...fresh,...previous].slice(0,3).map(song=>song.id)}else reviewSelection=pool.slice(0,3).map(song=>song.id);return reviewSelection.map(id=>byId.get(id)).filter(Boolean)}
function shuffleReviewSuggestions(){suggestedReviewSongs(true);render();toast('已换一组复习歌曲')}
function dateText(t){if(!t)return '还没练过';const d=new Date(t);return `${d.getMonth()+1}月${d.getDate()}日`}
function songCard(s){return `<article class="review-card"><button class="review-main" data-practice="${s.id}">${songCover(s,'review-thumb')}<span class="review-copy"><strong>${esc(s.title)}</strong><small>${esc(s.artist)}</small><span class="review-meta">${esc(s.genres[0]||s.type)} · ${dateText(lastLog(s.id)?.completedAt)}</span></span></button><div class="review-actions"><button class="review-play" data-practice="${s.id}">复习</button><button class="review-more" data-song="${s.id}" aria-label="查看${esc(s.title)}">•••</button></div></article>`}
function recentRow(s){const l=lastLog(s.id);return `<a class="recent-row" href="#/song/${s.id}">${songCover(s,'thumb')}<strong>${esc(s.title)}</strong><span class="meta">${esc(s.artist)}</span><span class="meta">${dateText(l?.completedAt)}</span><span>•••</span></a>`}
function learningRow(s){return `<article class="learning-row"><button class="learning-main" data-practice="${s.id}">${songCover(s)}<span><strong>${esc(s.title)}</strong><small>${esc(s.artist)} · ${dateText(lastLog(s.id)?.completedAt)}</small></span></button><button class="learned-button" data-learned="${s.id}">我会了</button></article>`}
function home(){const recent=songs.filter(s=>lastLog(s.id)).sort((a,b)=>lastLog(b.id).completedAt-lastLog(a.id).completedAt);const review=suggestedReviewSongs();const learning=songs.filter(s=>s.mastery==='正在学').sort((a,b)=>b.updatedAt-a.updatedAt);return shell(`<div class="page"><section class="hero"><img src="./assets/guitar-room.jpg" alt="阳光下的木吉他和绿植"><div class="hero-copy"><h1>晚上好 <span aria-hidden="true">🎸</span></h1><p>今天想弹什么？</p></div></section><div class="home-search search"><input id="home-search" aria-label="搜索歌曲或歌手" placeholder="搜索歌曲 / 歌手"></div><div class="quick-grid"><button class="quick-card" data-quick="random"><span class="quick-icon quick-random">${quickIcon('random')}</span><strong>随机一首</strong><span>发现新歌</span></button><button class="quick-card" data-quick="old"><span class="quick-icon quick-old">${quickIcon('old')}</span><strong>很久没弹</strong><span>超过 ${LONG_UNPLAYED_DAYS} 天</span></button><button class="quick-card" data-quick="master"><span class="quick-icon quick-master">${quickIcon('master')}</span><strong>拿手歌</strong><span>“很熟”后自动归入</span></button><button class="quick-card" data-quick="learning"><span class="quick-icon quick-learning">${quickIcon('learning')}</span><strong>最近在学</strong><span>继续练习</span></button></div>${songs.some(s=>s.demo)?`<div class="notice"><span>已放入少量原创示例内容，方便你体验完整流程。</span><button class="text-link" id="clear-demo">清除示例</button></div>`:''}<section class="section learning-section"><div class="section-head"><div><h2>最近新学</h2><p>只显示“正在学”的曲目，学会后点“我会了”</p></div>${learning.length?`<button class="text-link" data-learning-random>随机练一首 ›</button>`:''}</div>${learning.length?`<div class="learning-list">${learning.slice(0,5).map(learningRow).join('')}</div>`:`<div class="empty compact"><h3>暂时没有新学曲目</h3><p>添加乐谱时选择“正在学”，就会出现在这里。</p></div>`}</section><section class="section"><div class="section-head"><div><h2>今天建议复习</h2><p>从未完成过练习，或超过 ${LONG_UNPLAYED_DAYS} 天没练</p></div>${review.length?`<div class="review-head-actions"><button class="review-refresh" data-review-shuffle>${icon('shuffle')}<span>随机换一组</span></button><button class="text-link" data-quick="old">开始复习 ›</button></div>`:''}</div>${review.length?`<div class="review-grid">${review.map(songCard).join('')}</div>`:`<div class="empty compact"><h3>目前没有长期未练的歌曲</h3></div>`}</section><section class="section"><div class="section-head"><h2>最近弹过</h2><span class="local-badge">${icon('monitor')}本机记录</span></div>${recent.length?`<div class="recent-list">${recent.slice(0,4).map(recentRow).join('')}</div>`:`<div class="empty"><div>${icon('music')}</div><h3>还没有练习记录</h3><p>挑一首歌开始弹吧。</p></div>`}</section></div>`)}
function features(){const artists=[...new Set(songs.map(s=>s.artist))].sort((a,b)=>songs.filter(s=>s.artist===b).length-songs.filter(s=>s.artist===a).length);const tags=[...new Set(songs.flatMap(s=>s.tags))];return shell(`<div class="page features-page"><div class="top-row"><div><h1 class="title">功能</h1></div></div><div class="search"><input id="feature-search" placeholder="搜索歌曲 / 歌手"></div><div class="feature-grid section"><button class="feature-card" data-view="artist"><span class="feature-icon">${icon('user')}</span><span><strong>按歌手找</strong><p>先选择歌手，再查看对应曲目</p></span><span class="arrow">›</span></button><button class="feature-card" data-view="genre"><span class="feature-icon">${icon('music')}</span><span><strong>按曲风找</strong><p>流行、民谣、摇滚等</p></span><span class="arrow">›</span></button><button class="feature-card" data-view="type"><span class="feature-icon">${icon('guitar')}</span><span><strong>按类型找</strong><p>弹唱、指弹、Solo、练习曲</p></span><span class="arrow">›</span></button><button class="feature-card" data-view="mastery"><span class="feature-icon">${icon('bars')}</span><span><strong>按状态找</strong><p>拿手、基本会、复习、正在学</p></span><span class="arrow">›</span></button></div><div class="feature-section-title"><span class="quick-icon">${icon('star')}</span><div><h2>智能练习</h2><p>依据本机练习记录生成</p></div></div><div class="practice-grid"><button class="practice-item" data-quick="random"><span class="feature-icon">${icon('shuffle')}</span><span><strong>随机复习</strong><small>随机生成本次练习队列</small></span><span class="arrow">›</span></button><button class="practice-item" data-quick="old"><span class="feature-icon">${icon('clock')}</span><span><strong>长期未练</strong><small>从未练习或超过 ${LONG_UNPLAYED_DAYS} 天</small></span><span class="arrow">›</span></button><button class="practice-item" data-quick="learning"><span class="feature-icon">${icon('learn')}</span><span><strong>新歌练习</strong><small>只练“正在学”的曲目</small></span><span class="arrow">›</span></button><button class="practice-item" data-quick="master"><span class="feature-icon">${icon('heart')}</span><span><strong>拿手歌曲</strong><small>练习反馈为“很熟”的曲目</small></span><span class="arrow">›</span></button></div><div class="feature-section-title"><span class="nav-icon">${icon('tag')}</span><h2>我的标签</h2></div><div class="tag-cloud">${tags.map(t=>`<button class="tag-pill" data-tag="${esc(t)}">${esc(t)}</button>`).join('')}<button class="tag-pill" data-go-add>＋</button></div><div class="feature-section-title"><span class="nav-icon">${icon('user')}</span><h2>常用歌手</h2></div><div class="artist-row">${artists.map(a=>`<button class="artist-bubble" data-artist="${esc(a)}" style="border:0;background:none">${artistAvatar(a)}<span>${esc(a)}</span></button>`).join('')}</div></div>`)}
function browseView(group){const config={artist:['按歌手找','选择一位歌手','user'],genre:['按曲风找','选择一种曲风','music'],type:['按类型找','选择一种演奏类型','guitar'],mastery:['按状态找','选择当前熟练状态','bars']}[group]||['分类查找','选择分类','grid'];const values=unique(group);return shell(`<div class="page browse-page"><div class="browse-head"><button class="ghost" data-features-back>‹ 返回功能</button><div><h1 class="title">${config[0]}</h1><p class="subtitle">${config[1]}，再进入对应曲目</p></div></div>${values.length?`<div class="browse-grid">${values.map((v,i)=>{const count=songs.filter(s=>{const vals=group==='artist'?[s.artist]:group==='genre'?s.genres:group==='type'?[s.type]:[s.mastery];return vals.includes(v)}).length;return `<button class="browse-card" data-browse-group="${group}" data-browse-value="${esc(v)}">${group==='artist'?artistAvatar(v,'browse-symbol artist-photo'):`<span class="browse-symbol" style="--h:${18+i*37}">${icon(config[2])}</span>`}<span><strong>${esc(v)}</strong><small>${count} 首曲目</small></span><span class="arrow">›</span></button>`}).join('')}</div>`:`<div class="empty"><h3>这个分类还没有内容</h3><p>添加乐谱后会自动出现在这里。</p><button class="primary" data-go-add>添加乐谱</button></div>`}</div>`)}
function unique(key){return [...new Set(songs.flatMap(s=>key==='artist'?[s.artist]:key==='genre'?s.genres:key==='type'?[s.type]:key==='mastery'?[s.mastery]:s.tags))]}
function matches(s){const q=filters.search.trim().toLowerCase();if(q&&!([s.title,s.artist,s.type,s.mastery,...s.genres,...s.tags].join(' ').toLowerCase().includes(q)))return false;if(filters.favorite&&!s.favorite)return false;for(const [g,set] of Object.entries(filters.groups)){if(!set.size)continue;const vals=g==='artist'?[s.artist]:g==='genre'?s.genres:g==='type'?[s.type]:g==='mastery'?[s.mastery]:s.tags;if(![...set].some(v=>vals.includes(v)))return false}return true}
function libraryView(mode='all'){if(mode==='favorites')filters.favorite=true;if(mode==='history')filters.search='';const found=songs.filter(s=>matches(s)).filter(s=>mode==='history'?!!lastLog(s.id):true).sort((a,b)=>mode==='history'?(lastLog(b.id)?.completedAt||0)-(lastLog(a.id)?.completedAt||0):b.updatedAt-a.updatedAt);const groups=[['artist','歌手'],['genre','曲风'],['type','类型'],['mastery','状态'],['tag','标签']];return shell(`<div class="page"><div class="top-row"><div><h1 class="title">${mode==='favorites'?'收藏':mode==='history'?'练习记录':mode==='tags'?'我的标签':'我的曲谱'}</h1><p class="subtitle">${found.length} 首歌</p></div><button class="primary" data-go-add>＋ 添加乐谱</button></div><div class="toolbar"><div class="search"><input id="library-search" value="${esc(filters.search)}" placeholder="搜索歌曲 / 歌手 / 标签"></div><button class="filter-button ${filters.favorite?'active':''}" data-favorite>♡ 收藏</button></div>${mode==='tags'?`<div class="tag-cloud" style="margin-bottom:18px">${unique('tag').map(v=>`<button class="tag-pill ${filters.groups.tag.has(v)?'active':''}" data-filter="tag" data-value="${esc(v)}">${esc(v)}</button>`).join('')}</div>`:`<div class="filter-bar">${groups.map(([g,label])=>`<button class="filter-button ${filters.groups[g].size?'active':''}" data-filter-menu="${g}">${label}${filters.groups[g].size?` · ${filters.groups[g].size}`:''}</button>`).join('')}<button class="filter-button" data-clear>清除</button></div>`}<div id="filter-options"></div><div class="section">${found.length?`<div class="library-list">${found.map(s=>`<a class="library-row" href="#/song/${s.id}">${songCover(s)}<span class="library-title"><strong>${esc(s.title)} ${s.favorite?'♥':''}</strong><span>${esc(s.artist)}</span></span><span class="library-cell">${esc(s.genres.join('、'))}</span><span class="library-cell">${esc(s.type)}</span><span class="chip ${s.mastery==='正在学'?'orange':''}">${esc(s.mastery)}</span><span>›</span></a>`).join('')}</div>`:`<div class="empty"><div class="empty-search-icon">${icon('music')}</div><h3>没有找到合适的歌</h3><p>换个关键词，或者清除筛选后再看看。</p><button class="secondary" data-clear>清除筛选</button></div>`}</div></div>`)}
function addView(song=null){const editing=!!song;return shell(`<div class="page"><div class="top-row"><div><h1 class="title">${editing?'编辑乐谱':'添加乐谱'}</h1><p class="subtitle">乐谱会同步到你的设备；练习进度仍只保存在本机</p></div></div><form id="song-form" class="form-card"><div class="form-grid"><div class="field"><label for="title">歌名</label><input class="input" id="title" name="title" required value="${esc(song?.title||'')}" placeholder="例如：晴天"></div><div class="field"><label for="artist">歌手</label><input class="input" id="artist" name="artist" required value="${esc(song?.artist||'')}" placeholder="例如：周杰伦"></div><div class="field"><label for="genres">曲风</label><input class="input" id="genres" name="genres" value="${esc(song?.genres?.join('、')||'')}" placeholder="流行、民谣"></div><div class="field"><label for="type">类型</label><select class="select" id="type" name="type">${TYPES.map(v=>`<option ${song?.type===v?'selected':''}>${v}</option>`).join('')}</select></div><div class="field"><label for="mastery">本机熟练状态</label><select class="select" id="mastery" name="mastery">${MASTERY.map(v=>`<option ${(song?.mastery===v||(!song&&v==='正在学'))?'selected':''}>${v}</option>`).join('')}</select><small>新添加的乐谱默认归入“最近新学”</small></div><div class="field"><label for="tags">自定义标签</label><input class="input" id="tags" name="tags" value="${esc(song?.tags?.join('、')||'')}" placeholder="校园、聚会、睡前"></div><div class="field full"><label>谱图</label><label class="dropzone" id="dropzone"><input type="file" id="files" accept="image/jpeg,image/png,image/webp" multiple><strong>点击选择或拖入谱图</strong><p>支持 JPEG、PNG、WebP，每张不超过 15 MB</p></label><div class="preview-grid" id="preview-grid"></div></div><div class="field full"><label for="notes">个人备注</label><textarea class="textarea" id="notes" name="notes" placeholder="例如：副歌注意控制力度">${esc(song?.notes||'')}</textarea></div><div class="field full"><label><input type="checkbox" id="favorite" ${song?.favorite?'checked':''}> 加入收藏</label></div></div><div class="form-actions"><button type="button" class="ghost" data-cancel>取消</button><button class="primary" type="submit">${editing?'保存修改':'保存并同步'}</button></div></form></div>`)}
function demoScore(s){return `<div class="demo-score"><h2>${esc(s.title)}</h2><div class="score-meta">原创练习示意谱 · ${esc(s.artist)}</div><div class="chord-line">C　　　 G　　　 Am　　　F</div><div class="lyric-line">轻轻地拨响琴弦　让节拍慢慢流动</div><div class="chord-line">C　　　 G　　　 F　　　 C</div><div class="lyric-line">听见每一次呼吸　落在温柔的和弦中</div><div class="chord-line">Am　　　Em　　　F　　　 G</div><div class="lyric-line">保持稳定　再把旋律唱得从容</div><p style="margin-top:42px;color:#777;line-height:1.8">练习提示：先用 70 BPM 慢速完成两遍，再逐渐提速。示例谱不对应任何商业歌曲。</p></div>`}
function pageSource(page){if(!page)return'';if(page.blob){if(!scoreObjectUrls.has(page.id))scoreObjectUrls.set(page.id,URL.createObjectURL(page.blob));return scoreObjectUrls.get(page.id)}return page.remoteUrl||''}
function scorePreviewSource(song,pageIndex){return song.id.startsWith('import-')&&!song.localOverride&&pageIndex===0?`./assets/score-previews/${encodeURIComponent(song.id)}.webp`:''}
async function getScorePages(id){if(scorePageCache.has(id))return scorePageCache.get(id);const promise=repo.getPages(id).then(pages=>{scorePageCache.set(id,pages);return pages}).catch(error=>{scorePageCache.delete(id);throw error});scorePageCache.set(id,promise);return promise}
async function warmScore(id){warmPreview(id);const pages=await getScorePages(id);await Promise.all(pages.slice(0,2).filter(page=>page.remoteUrl).map(page=>fetch(page.remoteUrl,{cache:'force-cache'}).catch(()=>null)))}
function upgradeScoreImage(image,delay=700){const full=image.dataset.fullSrc;if(!full||full===image.currentSrc||full===image.src)return;const load=()=>{const highResolution=new Image();highResolution.decoding='async';highResolution.onload=()=>{if(!image.isConnected)return;image.src=full;image.removeAttribute('data-full-src');image.classList.add('high-resolution')};highResolution.src=full};if('requestIdleCallback'in window)requestIdleCallback(load,{timeout:delay+900});else setTimeout(load,delay)}
function warmPreview(id){if(!id?.startsWith('import-')||previewWarmers.has(id))return;const image=new Image();previewWarmers.set(id,image);image.onload=image.onerror=()=>setTimeout(()=>previewWarmers.delete(id),15000);image.src=`./assets/score-previews/${encodeURIComponent(id)}.webp`}
function warmHomePreviews(){const learning=songs.filter(song=>song.mastery==='正在学').sort((a,b)=>b.updatedAt-a.updatedAt).slice(0,5),review=suggestedReviewSongs();[...new Set([...learning,...review].map(song=>song.id))].forEach(warmPreview)}
function scorePagesHtml(song,pages,mode){if(!pages.length)return `<div class="${mode==='practice'?'practice-page current-mobile':'score-sheet'}">${demoScore(song)}</div>`;return pages.map((page,index)=>{const full=pageSource(page),preview=scorePreviewSource(song,index)||full,attrs=preview!==full&&full?`data-full-src="${esc(full)}"`:'';if(mode==='practice')return `<div class="practice-page ${index===0?'current-mobile':''}" data-page="${index}"><div class="score-loading">正在打开谱面…</div><img src="${esc(preview)}" ${attrs} loading="${index?'lazy':'eager'}" fetchpriority="${index?'auto':'high'}" alt="${esc(song.title)} 第${index+1}页乐谱"></div>`;return `<div class="score-sheet"><img src="${esc(preview)}" ${attrs} loading="${index?'lazy':'eager'}" fetchpriority="${index?'auto':'high'}" alt="${esc(song.title)} 第${index+1}页乐谱"></div>`}).join('')}
function instantScoreHtml(song,mode){const preview=scorePreviewSource(song,0);if(!preview)return `<div class="${mode==='practice'?'practice-page current-mobile':'score-sheet'} score-awaiting"><div class="score-loading">正在打开谱面…</div></div>`;return mode==='practice'?`<div class="practice-page current-mobile" data-page="0"><div class="score-loading">正在打开谱面…</div><img src="${esc(preview)}" loading="eager" fetchpriority="high" alt="${esc(song.title)} 乐谱预览"></div>`:`<div class="score-sheet"><img src="${esc(preview)}" loading="eager" fetchpriority="high" alt="${esc(song.title)} 乐谱预览"></div>`}
function prepareScoreImages(root=document,practice=false){$$('img',root).forEach(image=>{let timer;const ready=()=>{clearTimeout(timer);image.classList.add('loaded');image.previousElementSibling?.remove();if(practice){fitPracticeImage(image);applyPracticeZoom(practiceZoom)}upgradeScoreImage(image)};const fallback=()=>{const full=image.dataset.fullSrc;if(full&&image.src!==full&&!image.dataset.fallbackTried){image.dataset.fallbackTried='1';image.src=full;return}clearTimeout(timer);image.previousElementSibling?.remove();image.classList.add('load-failed')};image.addEventListener('load',ready,{once:true});image.addEventListener('error',fallback);timer=setTimeout(()=>{if(!image.classList.contains('loaded'))fallback()},7000);if(practice)image.addEventListener('dblclick',()=>applyPracticeZoom(100));if(image.complete)(image.naturalWidth?ready():fallback())})}
function detailView(id){const s=songs.find(x=>x.id===id);if(!s){location.hash='#/library';return}$('#app').innerHTML=shell(`<div class="page"><div class="top-row"><button class="ghost" data-back>‹ 返回</button></div><div class="detail-grid"><div class="score-stack">${instantScoreHtml(s,'detail')}</div><aside class="detail-panel"><h1>${esc(s.title)}</h1><div class="artist">${esc(s.artist)}</div><div class="chips">${s.genres.map(x=>`<span class="chip">${esc(x)}</span>`).join('')}<span class="chip orange">${esc(s.mastery)}</span>${s.tags.map(x=>`<span class="chip">${esc(x)}</span>`).join('')}</div>${s.notes?`<div class="detail-note">${esc(s.notes)}</div>`:''}<p class="count">最近练习：${dateText(lastLog(s.id)?.completedAt)}</p><div class="detail-actions"><button class="primary" data-practice="${s.id}">▶ 开始练习</button><button class="ghost" data-edit="${s.id}">✎ 编辑资料与谱图</button><button class="danger" data-delete="${s.id}">删除歌曲</button></div></aside></div></div>`);prepareScoreImages($('.score-stack'));bindCommon();getScorePages(id).then(pages=>{if(route()!==`/song/${id}`)return;const stack=$('.score-stack');stack.innerHTML=scorePagesHtml(s,pages,'detail');prepareScoreImages(stack)}).catch(()=>toast('谱图暂时无法打开'))}
function practiceView(id){const s=songs.find(x=>x.id===id);if(!s){location.hash='#/library';return}mobilePage=0;practiceZoom=100;$('#app').innerHTML=`<main class="practice-screen"><div class="practice-top"><button class="secondary" data-exit>‹ <span class="button-text">退出</span></button><div class="practice-title"><h1>${esc(s.title)}</h1><p>${esc(s.artist)} · <span data-page-count>1</span> 页</p></div><div class="score-tools"><button data-zoom-out aria-label="缩小谱面">−</button><span data-zoom-label>100%</span><button data-zoom-in aria-label="放大谱面">＋</button><button data-fit>适合屏幕</button><button data-fullscreen>全屏</button></div></div><div class="practice-hint">Ctrl + 滚轮缩放谱面 · 点击谱面显示操作栏 · 双击恢复整页</div><div class="practice-pages">${instantScoreHtml(s,'practice')}</div><div class="practice-controls is-hidden" aria-hidden="true"><button class="ghost" data-prev>上一首</button><button class="ghost" data-next>下一首</button><button class="primary" data-complete="${s.id}">完成</button></div></main>`;bindPractice();getScorePages(id).then(pages=>{if(route()!==`/practice/${id}`)return;$('[data-page-count]').textContent=pages.length||1;const container=$('.practice-pages');container.innerHTML=scorePagesHtml(s,pages,'practice');prepareScoreImages(container,true)}).catch(()=>toast('谱图暂时无法打开'))}
function modal(html){const d=document.createElement('div');d.className='modal-backdrop';d.innerHTML=`<div class="modal">${html}</div>`;document.body.appendChild(d);d.addEventListener('click',e=>{if(e.target===d||e.target.closest('[data-close]'))d.remove()});return d}
function splitList(v){return [...new Set(v.split(/[、,，]/).map(x=>x.trim()).filter(Boolean))]}
function releaseDraft(){draftPages.forEach(p=>p.url&&URL.revokeObjectURL(p.url));draftPages=[]}
function renderPreviews(){const el=$('#preview-grid');if(!el)return;el.innerHTML=draftPages.map((p,i)=>`<div class="preview-page"><img src="${p.url}" alt="谱图第${i+1}页"><div class="preview-tools"><button type="button" data-move="${i}" data-dir="-1" aria-label="上移">←</button><span>${i+1}</span><button type="button" data-move="${i}" data-dir="1" aria-label="下移">→</button><button type="button" data-remove-page="${i}" aria-label="移除">×</button></div></div>`).join('')}
async function loadEditor(id){const s=songs.find(x=>x.id===id);if(!s)return;releaseDraft();const pages=await repo.getPages(id);draftPages=[];for(const page of pages){let blob=page.blob;if(!blob&&page.remoteUrl){const response=await fetch(page.remoteUrl);if(!response.ok)throw Error('谱图加载失败');blob=await response.blob()}draftPages.push({...page,blob,url:URL.createObjectURL(blob)})}$('#app').innerHTML=addView(s);bindCommon();bindForm(s);renderPreviews()}
function bindForm(existing=null){const form=$('#song-form');const dz=$('#dropzone');const input=$('#files');const addFiles=files=>{for(const file of files){if(!['image/jpeg','image/png','image/webp'].includes(file.type)){toast(`${file.name} 不是支持的图片格式`);continue}if(file.size>MAX_FILE){toast(`${file.name} 超过 15 MB`);continue}draftPages.push({id:uid('page'),fileName:file.name,mimeType:file.type,size:file.size,blob:file,createdAt:Date.now(),url:URL.createObjectURL(file)})}renderPreviews()};input.onchange=e=>addFiles(e.target.files);['dragenter','dragover'].forEach(t=>dz.addEventListener(t,e=>{e.preventDefault();dz.classList.add('drag')}));['dragleave','drop'].forEach(t=>dz.addEventListener(t,e=>{e.preventDefault();dz.classList.remove('drag')}));dz.addEventListener('drop',e=>addFiles(e.dataTransfer.files));form.addEventListener('click',e=>{const rem=e.target.closest('[data-remove-page]');if(rem){const i=+rem.dataset.removePage;URL.revokeObjectURL(draftPages[i].url);draftPages.splice(i,1);renderPreviews()}const mv=e.target.closest('[data-move]');if(mv){const i=+mv.dataset.move,j=i+(+mv.dataset.dir);if(j>=0&&j<draftPages.length){[draftPages[i],draftPages[j]]=[draftPages[j],draftPages[i]];renderPreviews()}}});form.onsubmit=async e=>{e.preventDefault();if(!draftPages.length){toast('请至少添加一张谱图');return}const f=new FormData(form),time=Date.now();const selectedMastery=f.get('mastery');const song={id:existing?.id||uid('song'),title:f.get('title').trim(),artist:f.get('artist').trim(),genres:splitList(f.get('genres')),type:f.get('type'),mastery:selectedMastery,initialMastery:existing?.initialMastery||selectedMastery,favorite:$('#favorite').checked,tags:splitList(f.get('tags')),notes:f.get('notes').trim(),coverUrl:existing?.coverUrl||'',artistImageUrl:existing?.artistImageUrl||'',catalogManaged:!!existing?.catalogManaged,remoteUpdatedAt:existing?.remoteUpdatedAt||0,localOverride:!!existing?.catalogManaged,createdAt:existing?.createdAt||time,updatedAt:time};try{await repo.saveSong(song);await repo.savePages(song.id,draftPages.map(({url,...p})=>p));await refresh();releaseDraft();toast(existing?'已保存到本机':'乐谱已添加到本机');location.hash=`#/song/${song.id}`}catch(err){toast(err?.name==='QuotaExceededError'?'设备存储空间不足，请减少图片':'保存失败，内容仍保留在页面中')}}}
function chooseQueue(id){let q;try{q=JSON.parse(sessionStorage.getItem('practice-queue')||'[]')}catch{q=[]}if(!q.includes(id))q=songs.map(s=>s.id);return q}
function movePractice(id,step){const q=chooseQueue(id),i=q.indexOf(id),next=q[(i+step+q.length)%q.length];location.hash=`#/practice/${next}`}
function fitPracticeImage(image){if(!image.naturalWidth||!image.naturalHeight)return;const page=image.closest('.practice-page'),availableWidth=Math.max(280,page.clientWidth-28),availableHeight=Math.max(280,window.innerHeight-(innerWidth<=860?170:190)),ratio=image.naturalWidth/image.naturalHeight,fitWidth=Math.min(availableWidth,availableHeight*ratio);image.dataset.fitWidth=fitWidth;image.style.width=`${Math.round(fitWidth*practiceZoom/100)}px`}
function applyPracticeZoom(value){practiceZoom=Math.max(50,Math.min(320,value));$$('.practice-page img').forEach(image=>{if(!image.dataset.fitWidth)fitPracticeImage(image);else image.style.width=`${Math.round(Number(image.dataset.fitWidth)*practiceZoom/100)}px`});const label=$('[data-zoom-label]');if(label)label.textContent=`${practiceZoom}%`}
function openCompletionModal(id){
 let selectedRating='';
 const dialog=modal(`<h2>这次弹得怎么样？</h2><p>选择反馈会更新这首歌的练习状态，也可以直接退出。</p><div class="rating-grid"><button class="rating" data-rating="熟练"><span>😄</span>很熟</button><button class="rating" data-rating="遗忘"><span>😐</span>有点忘</button><button class="rating" data-rating="重练"><span>😵</span>要重练</button></div><div class="completion-actions"><button class="ghost" data-continue-practice>继续练习</button><button class="primary" data-finish-exit>完成并退出</button></div>`);
 dialog.addEventListener('click',async event=>{
  const rating=event.target.closest('[data-rating]');
  if(rating){selectedRating=rating.dataset.rating;$$('[data-rating]',dialog).forEach(button=>button.classList.toggle('active',button===rating));return}
  if(event.target.closest('[data-continue-practice]')){dialog.remove();return}
  if(!event.target.closest('[data-finish-exit]'))return;
  if(selectedRating){await repo.recordPractice(id,selectedRating);await refresh();toast(selectedRating==='熟练'?'已归入拿手歌':'练习已记录')}
  dialog.remove();sessionStorage.removeItem('practice-queue');location.hash='#/'
 })
}
function bindPractice(){
 const screen=$('.practice-screen'),controls=$('.practice-controls');applyPracticeZoom(100);prepareScoreImages(screen,true);
 const showControls=visible=>{controls.classList.toggle('is-hidden',!visible);controls.setAttribute('aria-hidden',String(!visible))};
 $('[data-exit]').onclick=()=>{sessionStorage.removeItem('practice-queue');location.hash='#/'};
 $('[data-prev]').onclick=()=>movePractice(route().split('/').pop(),-1);$('[data-next]').onclick=()=>movePractice(route().split('/').pop(),1);
 $('[data-zoom-out]').onclick=()=>applyPracticeZoom(practiceZoom-20);$('[data-zoom-in]').onclick=()=>applyPracticeZoom(practiceZoom+20);$('[data-fit]').onclick=()=>applyPracticeZoom(100);
 $('[data-fullscreen]').onclick=async()=>{if(document.fullscreenElement)await document.exitFullscreen();else await screen.requestFullscreen()};
 screen.addEventListener('click',event=>{if(!event.target.closest('.practice-page'))return;showControls(controls.classList.contains('is-hidden'))});
 screen.addEventListener('wheel',event=>{if(!event.ctrlKey)return;const page=event.target.closest('.practice-page');if(!page)return;event.preventDefault();const before=practiceZoom,rect=page.getBoundingClientRect(),focusX=event.clientX-rect.left+page.scrollLeft,focusY=event.clientY-rect.top+page.scrollTop;applyPracticeZoom(practiceZoom+(event.deltaY<0?25:-25));const ratio=practiceZoom/before;page.scrollLeft=focusX*ratio-(event.clientX-rect.left);page.scrollTop=focusY*ratio-(event.clientY-rect.top)},{passive:false,capture:true});
 window.onresize=()=>{$$('.practice-page img').forEach(image=>fitPracticeImage(image));applyPracticeZoom(practiceZoom)};
 document.onkeydown=event=>{if(event.key==='+')applyPracticeZoom(practiceZoom+20);if(event.key==='-')applyPracticeZoom(practiceZoom-20);if(event.key==='Escape'&&!document.fullscreenElement)location.hash='#/'};
 $('[data-complete]').onclick=event=>openCompletionModal(event.currentTarget.dataset.complete)
}
function clearFilters(){filters={search:'',groups:{artist:new Set(),genre:new Set(),type:new Set(),mastery:new Set(),tag:new Set()},favorite:false}}
function quick(kind){let pool=[...songs];if(kind==='old')pool=longUnplayedSongs();if(kind==='master')pool=pool.filter(s=>s.mastery==='拿手歌');if(kind==='learning')pool=pool.filter(s=>s.mastery==='正在学');if(!pool.length){toast(kind==='old'?`没有超过 ${LONG_UNPLAYED_DAYS} 天未练的歌曲`:'这个分类里还没有歌曲');return}if(kind==='random'){const previous=sessionStorage.getItem('last-random');pool=pool.filter(s=>s.id!==previous).concat(pool.filter(s=>s.id===previous));pool.sort(()=>Math.random()-.5);if(pool.length>1&&pool[0].id===previous)[pool[0],pool[1]]=[pool[1],pool[0]];sessionStorage.setItem('last-random',pool[0].id)}sessionStorage.setItem('practice-queue',JSON.stringify(pool.map(s=>s.id)));location.hash=`#/practice/${pool[0].id}`}
async function markLearned(id){const song=await repo.getSong(id);if(!song)return;await repo.saveSong({...song,mastery:'基本会',updatedAt:Date.now()});await refresh();render();toast(`《${song.title}》已移出最近新学`)}
function bindCommon(){$$('[data-go-add]').forEach(b=>b.onclick=()=>location.hash='#/add');$$('[data-go-library]').forEach(b=>b.onclick=()=>location.hash='#/library');$$('[data-practice]').forEach(b=>b.onclick=()=>quickSong(b.dataset.practice));$$('[data-song]').forEach(b=>b.onclick=()=>location.hash=`#/song/${b.dataset.song}`);$$('[data-quick]').forEach(b=>b.onclick=()=>quick(b.dataset.quick));$$('[data-review-shuffle]').forEach(b=>b.onclick=shuffleReviewSuggestions);$$('[data-learning-random]').forEach(b=>b.onclick=()=>quick('learning'));$$('[data-learned]').forEach(b=>b.onclick=()=>markLearned(b.dataset.learned));$$('[data-back]').forEach(b=>b.onclick=()=>history.back());$$('[data-features-back]').forEach(b=>b.onclick=()=>location.hash='#/features');$$('[data-cancel]').forEach(b=>b.onclick=()=>history.back());$$('[data-edit]').forEach(b=>b.onclick=()=>location.hash=`#/edit/${b.dataset.edit}`);const del=$('[data-delete]');if(del)del.onclick=()=>{const id=del.dataset.delete,s=songs.find(x=>x.id===id);const d=modal(`<h2>删除《${esc(s.title)}》？</h2><p>歌曲资料、谱图和练习记录都会从这台设备上删除，无法恢复。</p><div class="form-actions"><button class="ghost" data-close>取消</button><button class="danger" data-confirm-delete>删除</button></div>`);$('[data-confirm-delete]',d).onclick=async()=>{await repo.deleteSong(id);await refresh();d.remove();toast('歌曲已删除');location.hash='#/library'}};const hs=$('#home-search');if(hs)hs.onkeydown=e=>{if(e.key==='Enter'){clearFilters();filters.search=e.target.value;location.hash='#/library'}};const fs=$('#feature-search');if(fs)fs.onkeydown=e=>{if(e.key==='Enter'){clearFilters();filters.search=e.target.value;location.hash='#/library'}};$$('[data-view]').forEach(b=>b.onclick=()=>location.hash=`#/browse/${b.dataset.view}`);$$('[data-browse-value]').forEach(b=>b.onclick=()=>{clearFilters();filters.groups[b.dataset.browseGroup].add(b.dataset.browseValue);location.hash='#/library'});$$('[data-tag]').forEach(b=>b.onclick=()=>{clearFilters();filters.groups.tag.add(b.dataset.tag);location.hash='#/library'});$$('[data-artist]').forEach(b=>b.onclick=()=>{clearFilters();filters.groups.artist.add(b.dataset.artist);location.hash='#/library'});const cd=$('#clear-demo');if(cd)cd.onclick=async()=>{for(const s of songs.filter(s=>s.demo))await repo.deleteSong(s.id);await refresh();render();toast('示例歌曲已清除')}}
function quickSong(id){warmScore(id);sessionStorage.setItem('practice-queue',JSON.stringify(songs.map(s=>s.id)));location.hash=`#/practice/${id}`}
function showFilter(group){const el=$('#filter-options');if(!el)return;el.innerHTML=`<div class="tag-cloud" style="margin:12px 0 18px">${unique(group).map(v=>`<button class="tag-pill ${filters.groups[group].has(v)?'active':''}" data-filter="${group}" data-value="${esc(v)}">${esc(v)}</button>`).join('')}</div>`;$$('[data-filter]',el).forEach(b=>b.onclick=()=>{const set=filters.groups[b.dataset.filter];set.has(b.dataset.value)?set.delete(b.dataset.value):set.add(b.dataset.value);render()})}
function bindLibrary(){const input=$('#library-search');input.oninput=e=>{filters.search=e.target.value;clearTimeout(bindLibrary.t);bindLibrary.t=setTimeout(render,120)};$$('[data-filter-menu]').forEach(b=>b.onclick=()=>showFilter(b.dataset.filterMenu));$$('[data-filter]').forEach(b=>b.onclick=()=>{const set=filters.groups[b.dataset.filter];set.has(b.dataset.value)?set.delete(b.dataset.value):set.add(b.dataset.value);render()});$$('[data-clear]').forEach(b=>b.onclick=()=>{clearFilters();render()});const fav=$('[data-favorite]');if(fav)fav.onclick=()=>{filters.favorite=!filters.favorite;render()};bindCommon()}
async function render(){const r=route();if(!r.startsWith('/add')&&!r.startsWith('/edit'))releaseDraft();if(r.startsWith('/practice/'))return practiceView(r.split('/').pop());if(r.startsWith('/song/'))return detailView(r.split('/').pop());if(r.startsWith('/edit/'))return loadEditor(r.split('/').pop());if(r.startsWith('/browse/')){$('#app').innerHTML=browseView(r.split('/').pop());bindCommon();return}if(r==='/add'){$('#app').innerHTML=addView();bindCommon();bindForm();return}if(r==='/features'){$('#app').innerHTML=features();bindCommon();return}if(r==='/library'){$('#app').innerHTML=libraryView();bindLibrary();return}if(r==='/favorites'){clearFilters();filters.favorite=true;$('#app').innerHTML=libraryView('favorites');bindLibrary();return}if(r==='/history'){$('#app').innerHTML=libraryView('history');bindLibrary();return}if(r==='/tags'){$('#app').innerHTML=libraryView('tags');bindLibrary();return}if(r==='/settings'){$('#app').innerHTML=shell(`<div class="page"><h1 class="title">设置</h1><div class="form-card section"><h2>设备本地存储</h2><p class="subtitle">谱图与练习记录只保存在当前浏览器。清除网站数据会删除曲库。</p><button class="danger" id="reset-all">清空本机曲库</button></div></div>`);$('#reset-all').onclick=()=>{const d=modal(`<h2>清空本机曲库？</h2><p>所有歌曲、谱图和练习记录都会永久删除。</p><div class="form-actions"><button class="ghost" data-close>取消</button><button class="danger" id="confirm-reset">确认清空</button></div>`);$('#confirm-reset').onclick=()=>{indexedDB.deleteDatabase(DB_NAME);localStorage.removeItem('xian-seeded');location.reload()}};return}$('#app').innerHTML=home();bindCommon();queueMicrotask(warmHomePreviews)}
function registerWebMCP(){const c=document.modelContext;if(!c?.registerTool)return;const ac=new AbortController();c.registerTool({name:'search_songs',title:'搜索弦库',description:'按歌名、歌手或标签搜索当前设备上的个人吉他曲库。',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async({query})=>(await repo.listSongs()).filter(s=>[s.title,s.artist,...s.tags].join(' ').includes(query)).map(s=>({id:s.id,title:s.title,artist:s.artist,mastery:s.mastery}))},{signal:ac.signal});c.registerTool({name:'record_guitar_practice',title:'记录练琴',description:'为指定歌曲记录一次练习反馈并更新熟练状态。',inputSchema:{type:'object',properties:{songId:{type:'string'},rating:{type:'string',enum:['熟练','遗忘','重练']}},required:['songId','rating'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async({songId,rating})=>{await repo.recordPractice(songId,rating);await refresh();render();return{songId,rating,status:'recorded'}}},{signal:ac.signal})}
async function init(){try{db=await openDB();await refresh();registerWebMCP();window.addEventListener('hashchange',render);render();await pullCatalog()}catch(err){console.error(err);$('#app').innerHTML=`<div class="loading">无法打开本地曲库，请确认浏览器允许网站存储。</div>`}}
init();
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();installPrompt=event;const button=$('[data-install]');if(button)button.hidden=false});
window.addEventListener('appinstalled',()=>{installPrompt=null;toast('弦库已安装到电脑')});
window.addEventListener('online',()=>db&&pullCatalog());
window.addEventListener('offline',()=>setSyncStatus('离线使用中','offline'));
document.addEventListener('click',event=>{if(event.target.closest('[data-install]'))installApp()});
function warmFromTrigger(event){const trigger=event.target.closest('[data-practice],[data-song],a[href^="#/song/"]');const id=trigger?.dataset.practice||trigger?.dataset.song||trigger?.getAttribute('href')?.split('/').pop();if(id){warmPreview(id);if(trigger?.dataset.practice)warmScore(id)}}
document.addEventListener('pointerover',warmFromTrigger);document.addEventListener('pointerdown',warmFromTrigger,{passive:true});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').then(registration=>{(registration.active||navigator.serviceWorker.controller)?.postMessage({type:'PRECACHE_PREVIEWS'})}).catch(error=>console.info('PWA cache unavailable:',error.message)));
window.addEventListener('load',()=>setTimeout(warmHomePreviews,100),{once:true});
